name: VM Deploy NodeBB

on:
  push:
    branches:
      - main
  workflow_dispatch:
    
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.17.0'
      
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_ADMIN }}
          password: ${{ secrets.ADMIN_PASSWORD }}
          script: | 
            mkdir -p code
            cd code
            if [ ! -d "${{ secrets.REPO_NAME }}" ]; then
              echo "Directory doesn't exist, cloning repository..."
              git clone https://github.com/${{ github.repository }}.git ${{ secrets.REPO_NAME }}
            fi
            cd ${{ secrets.REPO_NAME }}
            git pull origin main
            docker compose down
            docker compose --profile redis up --build -d